### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by piero-vic** [eapenzacharias/recipes-on-rails#12]
# Setup Kanban Board

[Link to project](https://github.com/eapenzacharias/recipes-on-rails/projects/1)
There are three members on the team.

**Comment by julie-ify** [comment]
Hi @piero-vic, @eapenzacharias, and @lu-jim, 

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
